# Site settings
title: Vend.Ninja
email: une6@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Soon
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  une6

# Build settings
markdown: kramdown
