# Site settings
title: Vend.Ninja
email: une6@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Soon
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://vend.ninja" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  une6

markdown: kramdown
permalink: pretty

sass:
  sass_dir: _sass
  style: compressed